### PR TITLE
Log start & end time for all failed runs

### LINKED ISSUE #246: failure due to bad nodename does not have start_time/end_time
when a job such as this runs, and `nodename` is bad (for example, it can also happen with `database` or `username` i believe), `cron.job_run_details` does not record a start or end time:

```
SELECT cron.schedule('this will fail', '* * * * *', 'call doesnotexist()');
```

result:

```
postgres=# select * from cron.job_run_details ;
-[ RECORD 1 ]--+----------------------------------------------------------------------------------------------------------
jobid          | 1
runid          | 1
job_pid        |
database       | postgres
username       | postgres
command        | call doesnotexist()
status         | failed
return_message | connection failed
start_time     |
end_time       |
```

shouldn't a `start_time` and `end_time` be recorded anyway?

we're developing in-house monitoring that runs, say, every hour... and want to check any records in `job_run_details` that fit the window of the last hour based on `now()`. we cannot do this with null date records...

thanks.

### PR DESCRIPTION
**Pull request by kketch**
Currently start and end times are not recorded in the `job_run_details` table for job runs that fail to start due to connection problems, lack of available background workers when background execution is enabled, or other early-stage failures occurring before the cron task is in progress. 

This change ensures that `start_time` & `end_time` are recorded for those failures. The intent is to guarantee that timestamps are always available in the log table once a job reaches a definitive state (`succeeded` / `failed`)

Fixes #246

### CODE REVIEW

File: src/pg_cron.c [hunk 1]
```diff
@@ -1540,10 +1539,10 @@ ManageCronTask(CronTask *task, TimestampTz currentTime)
 				break;
 			}
 
-			start_time = GetCurrentTimestamp();
+			task->lastStartTime = GetCurrentTimestamp();
```
Comment (marcoslot) [inline src/pg_cron.c:1542]: this should already be set when we change state to task->state = CRON_TASK_BGW_START;

seems a bit confusing to get another timestamp

removing this line and keeping the change below seems like a slight improvement

(probably lastStartTime was introduced after this line)
